name: invascan
networks:
  invascannet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.100

services:
  nginx_proxy:
    image: nginx
    restart: always
    networks:
      - invascannet

  invascanmssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: invascanmssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=G9e@7I4RiCT#
      - MSSQL_PID=Express
    networks:
      invascannet:
        ipv4_address: 192.168.1.102
    ports:
      - "1406:1433"
    volumes:
      - sql_data:/var/opt/mssql

  invascanapi:
    image: invascan/invascanapi:latest
    container_name: invascanapi
    restart: always
    depends_on:
      - invascanmssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=192.168.1.102;Database=InvascanDb;User Id=sa;Password=G9e@7I4RiCT#;
    networks:
      invascannet:
        ipv4_address: 192.168.1.103
    ports:
      - "8080:80"

  # invascanweb:
    # image: your-web-image
    # container_name: invascanweb
    # depends_on:
      # - invascanapi
    # networks:
      # invascannet:
        # ipv4_address: 192.168.1.4
    # ports:
      # - "3000:80"

volumes:
  sql_data:
